### ISSUE TITLE
Doesn't work with Sublime Text 3`

### ISSUE THREAD

**Issue by cztomczak** [jonschlinkert/sublime-swig#2]
Hi,

I've followed your instructions, a swig file is opened and View > Syntax is checked as "Swig". Unfortunately the syntax highlighting doesn't work, all I see is a white text:

```
%module wrappers  //name of the resulting GO package
%{
#include "include/internal/cef_types_wrappers.h"
%}

%include "include/internal/cef_types_wrappers.h"
```

**Comment by jonschlinkert** [comment]
Sorry, but what is this?

```
%module wrappers  //name of the resulting GO package
%{
#include "include/internal/cef_types_wrappers.h"
%}

%include "include/internal/cef_types_wrappers.h"
```

this isn't valid swig syntax for sure

**Comment by cztomczak** [comment]
Seems like there is more than one project that uses the "swig" word:
http://www.swig.org/ - that's the first result from google, and I was looking for highlighting for this.

Now that I scrolled down your README.md I see that this is completely different thing here, an html template system.

**Comment by jonschlinkert** [comment]
got it, no prob. good luck finding the right one!

**Comment by cztomczak** [comment]
Haven't yet found.

Sorry for the invalid issue.
