### ISSUE TITLE
Install for Sublime 2

### ISSUE THREAD

**Issue by fpoirier1** [jonschlinkert/sublime-swig#3]
How to install for Sumblime 2 ?

I can't find any folder named `packages` ...

Thanks !

**Comment by jonschlinkert** [comment]
You should be able to install with [package control](https://sublime.wbond.net/installation#st2). 

Just do `ctrl + shift + p` then select `install`.  After a few seconds ST will show the plugins available for installation, just select `sublime swig` and it should install. 

If this doesn't work please let me know and I'll look into it. Let me know if you need more help.

**Comment by fpoirier1** [comment]
I can't find anything about Swig in the plugin list.

**Comment by jonschlinkert** [comment]
Are you sure it's not installed already? It's possible that it this got un-registered somehow, but I want to make sure what the problem is first.

**Comment by fpoirier1** [comment]
Well here is the syntaxes list : 
![screen shot 2014-03-07 at 2 28 34 pm](https://f.cloud.github.com/assets/1587658/2361229/cbc5901a-a62e-11e3-9880-41eb223ebe8b.png)

and here is the plugins list : 

![image](https://f.cloud.github.com/assets/1587658/2361243/efb4149c-a62e-11e3-992e-61c79a1a201b.png)

**Comment by jonschlinkert** [comment]
Okay, thanks for double checking for me. looks like it's not registered anymore. I'll get it fixed. thanks for the heads up.

**Comment by fpoirier1** [comment]
No problem thank for the quick responses it is really appreciated.

**Comment by jonschlinkert** [comment]
:+1:
