### ISSUE TITLE
Syntax highlighting bug in ifs

### ISSUE THREAD

**Issue by dozoisch** [jonschlinkert/sublime-swig#6]
There seems to be a little bug with the if tags

```
{% if hello && world %}
{% if foo || bar %}
```

![if-tag](http://i.imgur.com/QDg9l8t.png)

The first condition is highlighted as expected but the second one (world or bar) isn't!

Doesn't seem to work with operators either like

```
{% if foo == bar %}
```

bar doesn't get highlighted

**Comment by jonschlinkert** [comment]
k, I'll get it fixed. thanks for reporting it
