### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by fritz-c** [jonschlinkert/sublime-swig#7]
Would you consider inserting snippets into this package? I've mostly worked with Twig until now, and the snippets in [that package](https://github.com/Anomareh/PHP-Twig.tmbundle) have saved me a lot of searching the keyboard for curly braces and percent signs.

**Comment by jonschlinkert** [comment]
absolutely, want to do a pr?

**Comment by fritz-c** [comment]
In the course of looking up the options for this, I found this Textmate package by the author of Swig.
https://github.com/paularmstrong/Swig.tmbundle

It appears that most of it is compatible with Sublime, save for the comments. Would you mind if I @ mention the author in this thread to talk about reusing a few of his resources (primarily snippets)?

**Comment by jonschlinkert** [comment]
:+1:  sure!

**Comment by fritz-c** [comment]
@paularmstrong
Would you mind if we recycled the snippets and indendation rules from [your Swig Textmate package](https://github.com/paularmstrong/Swig.tmbundle) to use in the Sublime Text package?

**Comment by erin-dot-io** [comment]
Any progress on this?

**Comment by thecodechef** [comment]
Hey just created sublime-swig-snippets I'm currently for merge to happen but anyone who is looking for swig snippets just run `bash git clone https://github.com/thecodechef/sublime-swig-snippets.git`

**Comment by fritz-c** [comment]
Closed on account of no response received from the author.
