### ISSUE TITLE
add to package control

### ISSUE THREAD

**Issue by mkeedlinger** [jonschlinkert/sublime-swig#8]
Please add this to [Package Control](https://sublime.wbond.net/)

i really really want it there

**Comment by gothy** [comment]
+1

**Comment by mkeedlinger** [comment]
this doesn't seem to be actively maintained. if we don't get a response soon I hope no one minds if i fork this and submit it myself?

**Comment by FREEZX** [comment]
After waiting for a response for this long, i think someone should do it already :)

**Comment by jonschlinkert** [comment]
Yeah, I haven't used swig in a while. Feel free to fork, or if you want I can make you a collaborator.

**Comment by enagorny** [comment]
I did it.

**Comment by mkeedlinger** [comment]
@enagorny awesome. Did you also fork the project?

**Comment by enagorny** [comment]
Yes. I did. https://packagecontrol.io/packages/Swig now points to my fork(https://github.com/enagorny/sublime-swig). With modified Readme,

**Comment by mkeedlinger** [comment]
Fantastic!
